# gateway.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: node:18
        command: ["node", "-e"]
        args:
          - |
            const http = require('http');
            const { request } = require('http');
            http.createServer((req, res) => {
              const reqOptions = {
                host: 'slow-api',
                port: 80,
                timeout: 5000 // Timeout in 5 seconds
              };
              const backendReq = request(reqOptions, backendRes => {
                backendRes.pipe(res);
              });
              backendReq.on('timeout', () => {
                res.writeHead(504);
                res.end('504 Gateway Timeout');
              });
              backendReq.on('error', (e) => {
                res.writeHead(502);
                res.end('Bad Gateway: ' + e.message);
              });
              backendReq.end();
            }).listen(3000);
        ports:
        - containerPort: 3000

