apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  loadBalancerIP: 172.19.255.100  # Make sure this is within your MetalLB IPAddressPool
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80

