apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python-prestop-app:latest
        imagePullPolicy: Never
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo 'preStop hook triggered'; sleep 10"]
