apiVersion: v1
kind: Pod
metadata:
  name: probe-demo
spec:
  containers:
  - name: demo-container
    image: probe-demo:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 5000
    readinessProbe:
      httpGet:
        path: /ready
        port: 5000
      initialDelaySeconds: 2
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
