apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Always  # Default setting
  containers:
    - name: my-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          sleep 10;


