apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: hashicorp/http-echo
      args:
        - "-text=Hello from Backend"
      ports:
        - containerPort: 5678
