apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
        - name: processor
          image: busybox
          command: ["sh", "-c", "while true; do echo processing; sleep 10; done"]
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
      nodeSelector:
        type: high-performance
