apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
spec:
  containers:
  - name: main-app
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
  - name: setup
    image: busybox
    command: ["sh", "-c", "echo 'Initializing...'; sleep 30; echo 'Setup Complete'"]
