apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: local-pv         # 🔥 force bind to your PV
  storageClassName: ""         # 🔥 must match (empty = no dynamic provisioning)

